# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: language-learning-platform-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: language-learning-platform
  template:
    metadata:
      labels:
        app: language-learning-platform
    spec:
      containers:
      - name: language-learning-platform
        image: language_learning_platform:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: language-learning-platform-service
spec:
  type: NodePort
  selector:
    app: language-learning-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
